### ISSUE TITLE
Mass import of legal matters

### ISSUE THREAD

**Issue by alfallouji** [Microsoft/mattercenter#125]
Hi All,

I was wondering if there is any existing tool in order to automate an initial mass import of legal matters into the matter center.

If there is no existing tool, is there any API that we could use in order to programmatically create matters? 

Thanks for your help,

**Comment by DaveyDoo** [comment]
There is a PowerShell script CreateSampleData and an associated exe that will create matters from the items in your MCDeploymentConfig.xslx Sample_Data sheet.  However, this script apparently has to be run separately from the main deployment.  (I was about to create an issue on this--you beat me!)  My guess is that you have to do the content type publishing, give that tiime to get done, and then you run CreateSampleData.ps1 and it will populate matters from your Sample_Data sheet.
Dave

**Comment by sunnymistry** [comment]
You can also find entire source code which creates Mass Matters over here: (https://github.com/Microsoft/mattercenter/tree/master/tree/master/cloud/src/Helper%20Utilities/Microsoft.Legal.MatterCenter.HelperUtilities/Microsoft.Legal.MatterCenter.CreateSampleData)

As DaveyDoo correctly mentioned, before running this tool, along with content type publishing you need to ensure following as well:
a. All required Site Collections are created
b. Correct Permission are applied so that the utility can create Matters
