### ISSUE TITLE
Hanging on Select Type of Matter on Create Matter Page

### ISSUE THREAD

**Issue by ccorneby** [Microsoft/mattercenter#127]
Anybody run into this issue?  When trying to create a new matter - the page is hanging and is just spinning on Select Type.  I have checked the termstore, the subarea of laws, the content types in hub, in the site collections, the azure website and url's.  It seems to be stuck retrieving the list from the termstore.

**Comment by JohnLeeNJ** [comment]
Yes - I have the exact same problem.  The dots are spinning next to Select Type, but in fact, nothing on the page works for me.  I tried the Client dropdown and it was empty.  It seems to be hung loading the page.  I have not been able to create any matters.
The same thing happens to me on all the Matter Center pages except for Home.aspx.  As soon as I try to access any of the other pages, the page hangs while loading.

**Comment by sunnymistry** [comment]
Since the Select Type of Matter is spinning indefinitely, the first thing I would check if you are getting any JS error message. If you are not receiving any JS error, the next thing to check would be the Azure Table Storage.

**Comment by DaveyDoo** [comment]
I'm seeing the same thing.  No JS error message.

**Comment by DaveyDoo** [comment]
Sunny: What should we check in the Azure Table Storage?  Check the connection string?

**Comment by JohnLeeNJ** [comment]
I am getting a JS error.  It is the same as what I described in issue #130.  I'm not sure this issue is directly related to the Select Type button - that just happens to be where the spinning dots are on the page.  Based on the errors I have seen, it seems that the page itself is never getting loaded.  Very similar to the problems I'm having with other pages.  As I noted in that issue, the URL to my UI site is correct in the web.config, but Azure doesn't seem to be reading it.

**Comment by sunnymistry** [comment]
@DaveyDoo All server side error messages are logged in Azure Table storage. There are 3 log tables which are created depending on where this unhandled exception occurs. So when you load the Create Matters page, I would check UI and Service Log tables to determine what kind of exception is thrown in which method. This will help determine one of the following:
1. Configuration issues in code or in taxonomy 
2. Access issues while reading data from taxonomy
3. If there are some special characters in taxonomy which is causing the break
4. The tenant is having some delays with Taxonomy API's

@JohnLeeNJ due to the issue #130 none of the pages will load for you, as the service is rejecting all requests from your website.

**Comment by ccorneby** [comment]
issue is fixed, originally thought the problem was the globalconstants, instrumentation key or searchresultresource id, but it was an access issue and we republished the xml and it works.

We are able to create matters.

**Comment by ccorneby** [comment]
we have Matter Center creation working on http://uwavedemo1407.sharepoint.com/

notify us and if anybody wants to see it working.
Carol
