### ISSUE TITLE
Setting Timezones

### ISSUE THREAD

**Issue by TacitIT** [Microsoft/mattercenter#174]
Our current Matter Center deployment utilises US format dates.

Where do updates/configuration changes need to be made to support alternative date formats?

**Comment by sunnymistry** [comment]
Just to understanding this, over here you are referring to Date's shown within Matter Center app and not the Dates show in O365 SharePoint Document library view. 

If it is associated with Matter Center App, there is a method called FormatDate in JS files which you can update to show date in required format.

If it is associated with O365 SharePoint Document library, this is something which should be done from Office Admin Portal.

**Comment by TacitIT** [comment]
There are three main locations at the moment:

1. Matter Center "homepage". Under my matters, modified date is show as Month/Day/Year

2. "Date Conducted" field within the New Matter (2. Assign Permissions) creation process. Currently mm/dd/yyyy

3. New Matter confirmation email shows the date of the conflict check as entered in 2.

Can all three above be addressed with the JS file modification?

**Comment by SwapnilM92** [comment]
Kindly refer to the comments under the locations mentioned above,
1.	Matter Center "homepage". Under my matters, modified date is show as Month/Day/Year  
The date displayed is customized explicitly in GridView.js in 'formatDate' function
 
![image](https://cloud.githubusercontent.com/assets/16336925/15651781/3d5aa056-269f-11e6-82b0-79a12d4aa211.png)

In order to change the date format, you have to update the logic present in this function to display date in required format.
2.	"Date Conducted" field within the New Matter (2. Assign Permissions) creation process. Currently mm/dd/yyyy
This field is not configurable; we display the date in default date format supported by jQuery datepicker.
To make it configurable we need to update MatterProvision.js ($ConflictCheckDate) to support custom date format.
Ref: http://stackoverflow.com/questions/9401249/setting-default-date-format-for-datepicker
Apart from that, there are date fields present at column level filters in Search Matter and Search Document (Outlook app), date format for these dates can be configured from resource file present in,
Utility > Constants.resx > DatePickerFormat 
 
![image](https://cloud.githubusercontent.com/assets/16336925/15651783/4131948c-269f-11e6-9e9c-dcd948bd2da7.png)
3.	New Matter confirmation email shows the date of the conflict check as entered in 2
 To change the date format, configuration change required in resource file present in Provider Service > Constants.resx > Matter_Center_Date_Format
 
![image](https://cloud.githubusercontent.com/assets/16336925/15651786/45382302-269f-11e6-932f-afe02069b7a8.png)

Specify a valid date format supported by the .NET DateTime object
Ref: https://msdn.microsoft.com/en-us/library/8kb3ddd4(v=vs.110).aspx
