### ISSUE TITLE
Windows 7 Visual Studio 2015

### ISSUE THREAD

**Issue by mm43838** [Microsoft/mattercenter#195]
We have been unsuccessful with using webdeploy in Visual Studio to deploy the Matter Center solution in our environment. The FTP deploy method works for some of it but webdeploy does not work for any of it.  Is this only supported on Windows 10?

**Comment by amitabhm21** [comment]
This issue is not related to Matter Center. It seems that the issue is with your firewall blocking the network port that Visual Studio uses for Web Deploy.

Would you please check your firewall settings ? This can also happen if you use your corporate OS image for the development machine as that image can have ports blocked as part of the policy

This is not a Matter Center or Visual Studio issue.

**Comment by amitabhm21** [comment]
Hi @mm43838 do you have any further questions on this ?

**Comment by mm43838** [comment]
I concur with your findings.  We are likely being blocked by firewall or
policy.  Thank you.

On Wed, May 25, 2016 at 1:51 PM, Amitabh Mukherjee <notifications@github.com
