### ISSUE TITLE
General improvements

### ISSUE THREAD

**Issue by PieterVeenstra** [Microsoft/mattercenter#36]
While I've tried to install the matter center and while I've been debugging the PowerShell scripts I've got the feeling that the installation part of the solution could be improved quite a lot. I've not been able to get the actual solution up and running yet so I can't comment on that.
1. Settings are all over the place and repeated. A single configuration file would be helpful. Simple xml rather than an excel would be great. Updating code from GitHub is now a difficult task as settings need to be updated. Also if I contribute to the solution I will first have to take my settings out etc.
2. The creation of the sites should use the PnP provisioning engine.
3. There are a lot of PowerShell scripts (.ps1 files). The solution would become a lot better to manage if Modules were used.

**Comment by StationaryDave** [comment]
I will concur on Pieter's suggestions. 
As for No 1, it would be helpful if we could search and replace across the solution in order to insert the Azure site name, etc., but the extra comments in the files inhibit this.
For example, in the OneDriveRibbon AppManifest.xml, there is the text: [Enter URL of briefcase operations page. e.g. https://[SITENAME].azurewebsite.net/Pages/BriefcaseOperations.aspx?{StandardTokens}]
But if this text was "https://[AZUREUISITENAME].azurewebsite.net/Pages/BriefcaseOperations.aspx?{StandardTokens}"
it would be possible to search and replace "[AZUREUISITENAME]" with "MyUISite" and it wouldn't be necessary to delete the text "[Enter URL of briefcase operations page. e.g. " and to remember to delete the "]" at the end.

**Comment by PieterVeenstra** [comment]
One more improvement from my side. I also would like to see all deployment files to be part of the solution. Copying whole projects into a deployment folder makes it difficult to maintain the right versions of things. For an initial deployment this could work, but on the long run this deployment methodology will be a nightmare. When I update a file in the source code rebuild the code then which files do I need to copy where?
I would propose that we create a deployment folder within the solution and then use post build commands to copy things into the right place.

**Comment by amitabhm21** [comment]
@PieterVeenstra Thanks for your feedback. Your inputs are now implemented. Please check-out the new release.
