### ISSUE TITLE
MC 2 - Deployment guide: Install-Module AzureRM -AllowClobber’ failed

### ISSUE THREAD

**Issue by luismanez** [Microsoft/mattercenter#379]
I'm trying to deploy version 2 in a clean tenant (I was succesful with version 1 some months ago). I'm following deployment guide, and posting any issue I found (I'll try to help with the fixes). So:

I'm running this PS command in a PS console using Windows 10:
```
Install-Module AzureRM -AllowClobber’ 
```
but getting an error saying the param AllowClobber is not available.

In my case, has been enough with just removing the param, and the Module seems installed. Not sure why that param is required, but a note in the guide would be good.

Thanks.

**Comment by kmn-wsc** [comment]
I ran into the same issue. Resolved when I updated my development machine to the latest Windows Management Framework 5.0. I cannot confirm you need the entire framework or just an updated PowerShell but the -AllowClobber parameter was available with the Import-PSSession cmdlet after I updated. 

You can use the cmdlet without the AllowClobber parameter but you only get a partial install of the azureRm module.  

https://www.microsoft.com/en-us/download/details.aspx?id=50395  

Hope this helps.

**Comment by luismanez** [comment]
Thanks Kevin. yeah, I run it without that param, and seems worked fine. Now I'm finding more and more issues. They updated the master brach some hours ago, and now I'm trying a new clean deploy to see if it works fine. Have you installed version 2? when? worked fine?

**Comment by kmn-wsc** [comment]
Not yet, had multiple issues throughout the install as well. We are going to let Wilson and the team get some things updated and try again next week.

**Comment by luismanez** [comment]
yup, clever decission. I'm about to do that to. With latest version (8 hours ago), seems much better, but I'm still finding some issues related with trying to register the SP App while running the Azure deployment scripts...
Good to know I'm not alone :)

/cc @WilsonReddy

**Comment by amitabhm21** [comment]
These issues are now fixed. Would you please comment on this thread to validate and raise issues if you find any other issues ?

Appreciate your help !

**Comment by luismanez** [comment]
Hi @amitabhm21 How has been fixed? not sure how to validate it, as I already run the script without the AllowClobber param, and worked fine

**Comment by justinkobel** [comment]
@luismanez - I was just able to get the latest changes (checked in about 24 hours ago), and with the latest updates to the Deploy-AzureResourceGroups and the KeyVault-Config over the past week, I am now able to deploy the MC2 assets correctly.  I did have to recycle the Azure Web App twice to get the /api/ endpoints to pick up; and it took about 30 minutes for the Azure AD delegated permissions to take effect in my tenant and not throw AAD access errors.  
Also note that you have to configure the client settings first before generating a new matter (since if you don't explicitly configure each client in the UI, the MatterID field will be disabled and not visible); but otherwise it's looking good so far.

**Comment by luismanez** [comment]
That's great info @justinkobel Thank you very much! I'll give it a try as soon as I can.
Thanks again, really appreciate it. Considering your post, I'm gonna close this issue.

**Comment by mobiledevco** [comment]
Not to sound dumb as I am new to MC, but how do I configure the client settings so that I can create new matters?
