### ISSUE TITLE
Error in PreRequisitesScript.ps1

### ISSUE THREAD

**Issue by StationaryDave** [Microsoft/mattercenter#38]
Line 230 appears to be checking the value $SharePointURL in MCDeploymentConfig.xlsx, however it appears that no such field exists.
As a result the script outputs:  Running SharePoint Version check for False...
So when it passes this value to the CheckSharePointVersion function, it throws this exception:  Exception calling "Create" with "1" argument(s): "Invalid URI: The format of the URI could not be determined."

(I have more!)

**Comment by LeoConniff** [comment]
The error you are encountering is most likely because the url is not correct in the configuration spreadsheet.  Do you have any trailing '/'s at the end of the Tenant URL field and is it correct?  That can cause issues in the script.  The SharePoint URL is set on line 184 of the prereq script:
$SharePointURL = $ExcelValues[0]

$ExcelValues[0] = "TenantURL" from the spreadsheet and is assigned on line 177.

**Comment by StationaryDave** [comment]
Ahh, I see that $SharePointURL is a variable in the script.
However, I checked the xlsx and the TenantURL value is in the format "https://XYZ.sharepoint.com" with no trailing '/'s.
