### ISSUE TITLE
solution/Deployment/Scripts/Deploy-SPOFiles.ps1 | Extra Character

### ISSUE THREAD

**Issue by Majovero** [Microsoft/mattercenter#435]
![image](https://cloud.githubusercontent.com/assets/16903695/18879816/aade093a-84a3-11e6-9427-3c25a18be02d.png)

Caused non critical errors.

```
Show-Message : The term 'Show-Message' is not recognized as the name of a cmdlet, function, script file, or operable 
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At D:\Documents\MatterCenter\solution\Deployment\Scripts\Deploy-SPOFiles.ps1:24 char:1
+ Show-Message -Message "Adding common library functions" -Type ([Messa ...
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Show-Message:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by WilsonReddy** [comment]
@Majovero  you can ignore this message. if possible fix this in your fork by replacing show-message with Write-Output and make a pull request. appreciate your contribution.

**Comment by luismanez** [comment]
Actually, this issue is impacting my deployment process, as the LibraryFunctions are not being include in the Deploy-SPOFiles, and then, when that script calls the DeployOutlookApp.ps1, the Read-FromExcel function is not there, and the script fails. Please, could you submit a Pull Request with that fix?
Thanks.

**Comment by WilsonReddy** [comment]
@luismanez This issue was fixed few days back. Let me know if you still facing this issue.
