### ISSUE TITLE
Create Matter: ID field disappears on Client selection

### ISSUE THREAD

**Issue by atjohns2** [Microsoft/mattercenter#462]
When I select a Client from the dropdown, the Matter ID disappears but remains required and I cannot advance to the next screen. The only errors I see on the console are 404 related to the following JS files - /lib/bootstrap/dist/js/bootstrap-tooltip.js & bootstrap-popover.js

Not exactly sure why those aren't  getting deployed with the rest of the JS library files, or if its the cause of the application error itself or if there's just something going on in the createMatter.controller.js

![1475677751643](https://cloud.githubusercontent.com/assets/4114777/19117316/94eb3604-8ae6-11e6-82b5-8a7a508e9f88.jpg)

![1475677788302](https://cloud.githubusercontent.com/assets/4114777/19117344/ad3f6162-8ae6-11e6-97de-d3f27103054f.jpg)

Here's what the form field looks like - it contains both an ng-hide and an ng-invalid state.

![1475677898934](https://cloud.githubusercontent.com/assets/4114777/19117410/eb6c7128-8ae6-11e6-8975-7fb775cf451b.jpg)

**Comment by WilsonReddy** [comment]
@atjohns2  The Matter ID is disappearing because 'Show Matter ID?' would have set to no in settings.  follow below steps if you want to show Matter ID.
1. Go to settings page https://<<tenant name>>.sharepoint.com/SitePages/Settings.aspx
2.  Select your client(BCBSNC) and set show matter id to yes. Then it will show matter id.

The validation issue is fixed in latest drop. Take latest code and publish if you want to hide matter id.

**Comment by atjohns2** [comment]
Thanks!
