### ISSUE TITLE
WebSite/Service Must be Located in West US due to Hard-Coded Value in PublishOnAzure.ps1

### ISSUE THREAD

**Issue by DaveyDoo** [Microsoft/mattercenter#54]
Hard-coded values for Location/Affinity Group and Resource Group will cause a deployment failure if WebSite and Service are not located in "West US" and "Default-Web-WestUS"
It would be helpful if the Build and Deployment Guide noted this requirement or (even better) if the scripts were able to discover the correct Location and Resource Group for the sites.

**Comment by ajmeradivyesh** [comment]
While publishing on Azure, location and resource group of Radis cache gets set based upon the location of Azure sites. This hard coding is for the purpose of setting default values for location and resource group. Thus if the script is not able to get the value from Azure site, then this default location and ResourceGroupName will be used.
In order to update these default values, you can modify lines 38 and 39 in the PublishOnAzure.ps1 file.

**Comment by DaveyDoo** [comment]
Understood.  It might help if this is explained in the Build and Deployment Guide.

**Comment by amitabhm21** [comment]
The docs were updated. Closing this issue.
