### ISSUE TITLE
Web.EnsureUser fails when there is more than one match - prevents matter creation

### ISSUE THREAD

**Issue by johnnycardy** [Microsoft/mattercenter#57]
EnsureUser fails when there is more than one match. This can happen when:

- Two users have the same title
- One user has multiple accounts

The second situation applies to me; my SharePoint Online tenant knows about both my domain account and my Microsoft account, which of course have the same title.

`ValidateTeamMembers` should be using the Key that comes back from the People Picker search as the `EnsureUser` argument instead of title.

![image](https://cloud.githubusercontent.com/assets/904610/12260638/b0b4fc66-b914-11e5-8d98-ebbcc3d96c76.png)

![image](https://cloud.githubusercontent.com/assets/904610/12260349/5fbd053e-b913-11e5-98e5-91cc92f6eebd.png)

![image](https://cloud.githubusercontent.com/assets/904610/12260255/c951dc46-b912-11e5-827e-3db04df97209.png)

**Comment by sunnymistry** [comment]
Thank you Johnny for details around this. This issue happens because we are currently using the Users Name to determine whether the user exists or not. We are working on the build to update this implementation to make use of alias instead of User Name. Once this build is ready will be submit the pull request for the same
