### ISSUE TITLE
500 error issue faced after publishing solution

### ISSUE THREAD

**Issue by SumeshKashyap** [Microsoft/mattercenter#627]
Hello All,

I am facing a 500 error  after deploying the Microsoft.Legal.MatterCenter.Web project on Azure site.
We are using Trial version for Azure. Do we need some other subscription or plan (Basic,E3 etc)?
Also I am attaching a document which consist of logs and steps done by me to diagnose this.

Regards,
Sumesh Kashyap
[Troubleshooting.zip](https://github.com/Microsoft/mattercenter/files/696324/Troubleshooting.zip)

**Comment by WilsonReddy** [comment]
@SumeshKashyap Trial version should work. you need to set hosting environment to development to see error details. follow below steps for setting environment variable to development.
1. Go to https://portal.azure.com, Select web app (your web app is mattercenterweb01091018 appservice) under the resource group created as part of the deployment.
2. Go to application settings and add Hosting:Environment key with development value.
3. Now you will get more error details. ensure to access your web app with https(https://mattercenterweb01091018.azurewebsites.net)  

also, verify app service plan. The Scale up(App Service plan) should be B1 Basic.

**Comment by myao1** [comment]
@WilsonReddy I've run into the same problem as well. I've followed your instructions and added the new key-value to the application settings. I've attached the 500 error with stacktrace.
![mattercenter500](https://cloud.githubusercontent.com/assets/1839834/21990828/3aff6b62-dbde-11e6-9d9c-bbe16e644fc8.PNG)

**Comment by AISDUG** [comment]
From the stack trace it is failing because of one or both of the following. Either the KeyVaultClientID or Certificate are missing from App Settings for the App Service in Azure. These should have been added during the deployment.

General:KeyVaultClientID: This should be the ApplicationID of the AD Application 

General:KeyVaultCertThumbPrint: This should be the Thumbprint of the Certificate that was generated during the deployment.

General:KeyVaultURI : This should be the DNSName of your KeyVault. These should have been added by the deployment.

If you are running locally then these values need to be added to the appsettings.json in the General section.

Verify that the Certificate was uploaded to the app service by checking the SSL Certificates on the App Service

Also check to see if you followed the steps to generate the AppKey and that the script was run to add this value to the KeyVault . The value should be added to the General-AppKey secret while following the steps below.

Generate key 

- https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-authentication-scenarios#basics-of-registering-an-application-in-azure-ad
- Run script \tree\master\cloud\src\solution\Deployment\Scripts\keyVaultSecret.ps1 to update secret in keyVault

**Comment by myao1** [comment]
@AISDUG 
Thanks for your help. I've checked the App Settings for the App Service and I have all of those values as well as the certificate.  My Keyvault is also updated with the General-AppKey secret after generating the secret and running the script.

The exception changed slightly but it still seems the same: http://matterapp01242015.azurewebsites.net/

**Comment by AISDUG** [comment]
The deployment is targeted on win 10 client machines . Would really appreciate if you could fork and contribute for the Server side SKUS. 

Can you try creating your own SelfSigned certificate following the steps in this article. MakeCert should be available in 2012. I believe it should work for you
 
https://msdn.microsoft.com/en-us/library/ff699202.aspx

Then in the KeyVault-Config.ps1 script

Replace the line  that contains New-SelfSignedCertificate with  the below and replace the thumbprint with the thumbprint you created

Set-Location -Path "cert:\CurrentUser\My"
 $crt = (Get-ChildItem -Path E42DBC3B3F2771990A9B3E35D0C3C422779DACD7 )

**Comment by amitabhm21** [comment]
@myao1 Any updates on this?

**Comment by amitabhm21** [comment]
Closing this issue. Please re-open if needed.
