### ISSUE TITLE
Error Creating Matter

### ISSUE THREAD

**Issue by DaveyDoo** [Microsoft/mattercenter#63]
Error creating matter.  Nothing obvious on the browser end.  Nothing in the server logs.
![01](https://cloud.githubusercontent.com/assets/15142262/12495408/7c927742-c05d-11e5-8730-7006192b4660.png)

**Comment by dioulos** [comment]
DaveyDoo  If you put a breakpoint in the MatterProvision.js at the line after commonFunctions.createMatterSuccess (which should be: result = JSON.parse(result)) you should see the actual server error in a json format.

This one says:  

![image](https://cloud.githubusercontent.com/assets/11888581/12507890/86735cc0-c0f0-11e5-8731-a6a754eb499b.png)

I am still trying to resolve that issue...

**Comment by bblackwood1** [comment]
I am getting the same 404 issue as well... what is interesting is the fact that I am able to upload the sample data using the powershell script

**Comment by sunnymistry** [comment]
Can you check in your Azure Storage where exactly in code the error is thrown. You are getting 404 because it might not be able to find the content type in the site collection either because of following 2 reasons:
a.	The solution is not able to find the correct content type name group. The deployment scripts creates the group called _MatterCenter, but in the configuration file you will be having _LegalDMS in "One_Drive_Content_Type_Group" key in Microsoft.Legal.MatterCenter.ProviderService > Constants.resx
b.	The content types are not published because of which they are not available in the client site collection where you are trying to create the Matter

**Comment by bblackwood1** [comment]
@sunnymistry  so in my constants.resx file I have _LegalDMS... should that be _MatterCenter instead?

**Comment by dioulos** [comment]
@sunnymistry I have the content type and my constants.resx has the _MatterCenter but it still gives me the same error. :(

What I notice is that in the json object, sent has part of the CreateMatter web method call, has the following property:

"userId":["txtAssign1"],"hasErrorOccurred":false}

is it normal that userId is assigned to txtAssign1?


Also that same json object has a AssignUserNames which is empty:

"AssignUserNames":[["Dev 5",""]]

is this the normal structure?

**Comment by bblackwood1** [comment]
I am also still getting the same error with mattercenter instead of legaldms

**Comment by bblackwood1** [comment]
![mcerror8](https://cloud.githubusercontent.com/assets/16137126/12563496/28586c7a-c370-11e5-8a96-bb58ea947924.png)
Also here is my log for the error if that helps at all like dioulos said its an issue with creatematter method

**Comment by bblackwood1** [comment]
@sunnymistry Okay I found part of my problem here... I am a little dumb around the edges.  I looked into my matter center service web bin folder and looked at the constants file and behold the provision matter app url was incorrect here too.  So once I changed that it got me past that issue.

**Comment by bblackwood1** [comment]
Now I have a new issue... it made it to step 3 of the create matter and failed. 
![mcerror9](https://cloud.githubusercontent.com/assets/16137126/12585355/5331dcaa-c411-11e5-8a9b-35c2e1ff94e0.png)

**Comment by DaveyDoo** [comment]
I think I can help you!
There is some additional setup mapping you need to do. 
In contentTypeHub, Site Settings, Site Columns, change the AreaOfLaw Term Set setting from Practice Group to Litigation, and change the SubAreaOfLaw Term Set setting from Practice Group to Intellectual Property.  Then republish all the content types, wait for an hour or so, and you should be able to create matter. 
Apparently, just because the Term Store hierarchy is populated correctly and the Select a Practice Group dialog behaves correctly, you still need to map the columns.

**Comment by bblackwood1** [comment]
I will try that right now and let you know what happens for me
Thank you for your help

**Comment by bblackwood1** [comment]
DAVE!!!!! you are amazing.  Thanks for your help there.  I am now able to create matters.

**Comment by dioulos** [comment]
ok bblackwood1 so how should the he provision matter app url looks like? 

currently it is:  https://mysharepointTenant.sharepoint.com/sites/appcatalog/ProvisionDMSMatter

**Comment by bblackwood1** [comment]
remove the ProvisionDMSMatter and replace it with MatterCenter

**Comment by bblackwood1** [comment]
I have not figured out why it puts that in there instead of matter center but once I do I will post about it.

**Comment by dioulos** [comment]
Still does not work....I changed the url to https://mysharepointTenant.sharepoint.com/sites/appcatalog and I was able to have a new error:  "Error in creation of matter: Incorrect inputs"

The main problem here is that there is so many pieces that I am certain I got all the piece in place.  I still have my "userId":["txtAssign1"] in the json sent to create the matter which I believe does not make sense as I would have excepted a number for the userId!?

Do you have a SendMail list in any of the site collections as it looks like a sendMail list need to exist somewhere since the description on the resource file for 'Provision_Matter_App_URL' says "App web URL where Send Mail list is located on SharePoint" ?

**Comment by bblackwood1** [comment]
did you change the url on both the matter center service and matter center constants.resx files?

**Comment by bblackwood1** [comment]
I did not put a send mail list in any of the collections... I figured the script was doing that

**Comment by dioulos** [comment]
yes I updated both constants.resx....yes that's what I am thinking aswell it might need the sendmail list to exist in order to complete the task correctly. Perhaps, the script did not create that sendmail list but I can see the list schema in the code base. I may have to reinstall or to find out where I need to create this sendmail list.

**Comment by dioulos** [comment]
Alright...I remove everything and started again. This time no hack or manual steps...playing only with the resource files and correcting some of the  (out of the box) spelling mistakes. 

Now It seems that I am pretty close to create a matter. I reached the second phase (2/3) of the CreateMatter process. 

I have a new error: (File Not found)

![image](https://cloud.githubusercontent.com/assets/11888581/12648087/2d9034ae-c5d0-11e5-9d9f-35a011a7007c.png)

Not sure which file I am missing?
Any ideas?

**Comment by DaveyDoo** [comment]
See my reply above.  You need to go back to the contentTypeHub and manually change the mappings for a couple of the managed metadata columns, then republish all the content types. And it will take 1-48 hours for SharePoint online to invoke your new settings.  Good luck and be careful out there.

**Comment by sunnymistry** [comment]
This would be because the either PracticeGroup, Area Of Law or Sub Area of Law Site columns are not mapped to current Term Store. Because of which when you are trying to create matters, it is not have to set default values of these site column based on our selection. 

Can you check if all of these site columns are in Content Type Hub are pointing to MatterCenterTerms term set in Taxonomy?

**Comment by dioulos** [comment]
Yes there are.... I just verified and PracticeGroup is pointing to "PraticeGroup" term set; AreaOfLaw is pointing to "litigation" (a term of PraticeGroup); and SubareaOfLaw is pointing to "intellectual property" (a sub term of SubareaOLaw)

![image](https://cloud.githubusercontent.com/assets/11888581/12929013/97f3bcde-cf68-11e5-9585-26fafd2d376d.png)

**Comment by sunnymistry** [comment]
Thank you for confirming on this as this is the issue. The Area of Law and Sub Area of Law should be pointing to Practice Group Term Sets itself in Content Type Hub. When you create Matters, Matter Center will automatically find correct mapping and set it in respective Document Library.

**Comment by dioulos** [comment]
Perfect it is working. I had to delete the locale storage of the previous matter "attempt" but then it went fine. Thanks for your help...all of you :)

PS: I think that some type of powershell that could do the repointing of metadata and do the republishing of content type might be needed at one point to ease the process.

**Comment by shak3800** [comment]
Can anyone please tell me how to create that SendMail list because the script hasn't created it ?
