### ISSUE TITLE
Index out of bounds for UpdateAppConfig in Deploy.ps1

### ISSUE THREAD

**Issue by myao1** [Microsoft/mattercenter#636]
In Deploy.ps1 on step 4, I'm getting an out of bounds message when calling the function UpdateAppConfig.exe.

When looking in the HelperUtilities solution at the UpdateAppConfig project, the Main method looks fine to me so I'm not sure what could be causing this problem.
![deploystep4](https://cloud.githubusercontent.com/assets/1839834/22352304/88b06b64-e3e9-11e6-9c2c-381806abc2f1.PNG)

**Comment by merill** [comment]
Looks like they forgot to update the power shell script that calls the .exe to include the new parameter. 
As a temporary fix change line 291 of Deploy.ps1 to pass in a "false" parameter.
It doesn't really matter what whether you pass true or false since the code that is using this parameter is currently redundant.
`& "$HelperPath\Microsoft.Legal.MatterCenter.UpdateAppConfig.exe" "3" $Username $Password "false"`

**Comment by WilsonReddy** [comment]
@myao1 @merill  Thanks for reporting this issue. we applied fix. In future, consider making pull requests for these kind of issues.
