### ISSUE TITLE
Add attachment issue

### ISSUE THREAD

**Issue by miloskerkez** [Microsoft/mattercenter#639]
Hi,
when I try to add an attachment to a new message from matter center add-in in OWA, error with message "One or more of your selected documents failed to attach:" popups. It seems that I can not attach files that are protected by sharepoint.

![attachissue](https://cloud.githubusercontent.com/assets/5363811/22423916/4a038b9a-e6f4-11e6-81c0-f63a3a2507f8.png)

Can someone help me with this problem, please?

**Comment by WilsonReddy** [comment]
@miloskerkez What is the error logged in azure storage table?

**Comment by miloskerkez** [comment]
@WilsonReddy There is no logged error in azure storage table. It seems that problem is in office.js method addFileAttachmentAsync. When I put public URL in that method, attachment is successfully uploaded, but when I try to put URL from SharePoint it breaks.

**Comment by premchandpl** [comment]
@miloskerkez In order to attach a file from matter web app to outlook, there is a requirement where first, we need to login into  MS word application using the login that you are using to login to matter web app. 
After login to MS Word using the matter web app login, try to do the same functionality and it should work.
This wont work in Outlook web access. It will work only in outlook client desktop app. 

Let me know if this helps?

**Comment by premchandpl** [comment]
@miloskerkez You can use any office application such as word or excel to login not just ms word

**Comment by premchandpl** [comment]
@miloskerkez I am closing this. Follow the steps that I have mentioned and it should resolve the issue
