### ISSUE TITLE
content types

### ISSUE THREAD

**Issue by ele11ven** [Microsoft/mattercenter#64]
has anyone had an issue when publishing the content types to a site where the managed metadata does not move over to the site columns?

**Comment by DaveyDoo** [comment]
Yes.  Once I went to contentTypeHub, Site Settings, Site Columns, and changed the AreaOfLaw Term Set setting from Practice Group to Litigation (or probably any node at that level), and changed the SubAreaOfLaw Term Set setting from Practice Group to Intellectual Property, then republished all the content types (and waited an hour), I was able to create a matter.

**Comment by ele11ven** [comment]
Thanks much for the reply!  I tried that and the columns are still not showing the managed metadata fields and I can't create a matter.  Do you have any other ideas?  Any help would be greatly appreciated!!!

**Comment by ccorneby** [comment]
we have changed the terms and it takes sometimes 24-48 hours for the terms to flush through the system.  Also, check your values in the custom property of the subarea of law term, the lowest node in the hierarchy and ensure there is a content type in the document site collections for both the subarea of law and documenttemplate

**Comment by sunnymistry** [comment]
When you update site content type within a Single site collection, SPO creates a local copy of this content type. In this case when you make updates in Content Type Hub and publish it, the changes might not reflect in this specific site collection due to local copy. 

So the work around would be to:
1. Un-publish content type from Content Type Hub
2. Validate that the Content Type is indeed removed from all site collections. If it is not removed, delete it explicitly. After this wait for timer job to complete its sync
3. Re-publish the updated Content Types from Content Type Hub

**Comment by ctrulove** [comment]
@ele11ven Pinging you to make sure you have the information that you need.

**Comment by amitabhm21** [comment]
Closing this issue as this seems to be resolved.
