### ISSUE TITLE
Matter Manage User is empty

### ISSUE THREAD

**Issue by przemasd** [Microsoft/mattercenter#658]
Hi, 
I have issue with Matter Manage User. Page is empty, probable URL was not mapping in JavaScript but I don't now what URL is correct. 

![image](https://cloud.githubusercontent.com/assets/25458793/22970697/4797a266-f373-11e6-95c1-e258f67f070b.png)

when I debugging js (_MatterLanding.js_) I see a line where URL to Manage Pages was creating but was wrong. 
![image](https://cloud.githubusercontent.com/assets/25458793/22970766/a8901166-f373-11e6-9047-c59df518899c.png)

**Comment by premchandpl** [comment]
The issue is with line 56. The value for managePermissions has to be like this ""managePermission": "/#/matterusers"

Download matterlanding.js file from catalog site collection, update that file with the above changes and upload the same

The path to matterlanding.js will be "SiteAssets/Matter Center Assets/Matter Landing Assets/Scripts/MatterLanding.js"

Let me know if this solve the issue

**Comment by przemasd** [comment]
This is what i needed to working this page. Thank you very much.
