### ISSUE TITLE
App isn't deploying to Exchange Online Add-In

### ISSUE THREAD

**Issue by ccorneby** [Microsoft/mattercenter#66]
Has anyone noticed that the Outlook app isn't being added during deployment?  We have noticed this the last 4 Office 365 E3 tenancy has had this happen?  We have one server which does the deployment, we have overwritten the xml file.  We are going to go back and handcraft the xml and upload to EAC.

**Comment by DaveyDoo** [comment]
The Outlook app (an add-in, to use the latest term) was deployed and is running in our tenancy.

**Comment by sunnymistry** [comment]
One of the cause where the app might not get deployed in the tenancy is because one or some of the users in the Excel file (who should have Exchange app installed) are:
a. Not present in the tenant
b. They do not have Exchange licenses

Carol if you can share the error from the scripts we will be able to pinpoint exact issue.

**Comment by ctrulove** [comment]
@ccorneby Pinging you to see if you have the information you need. If you are still experiencing issues, please let us know so that we can troubleshoot and resolve.
