### ISSUE TITLE
Matter Center Deployment

### ISSUE THREAD

**Issue by wauph** [Microsoft/mattercenter#662]
Hi there,

I am currently having issues on deployment. Is the document Build and deployment guide for office 365 up to date ?

Does Matter Center comes as an Add in in SharePoint online ? If yes, why it does not have an appmanifest.xml where I can put a clientID and ClientSecret.

Please help, Thanks in advance

Will

**Comment by premchandpl** [comment]
The matter center has been upgraded to V2 and there is no sharepoint add in for sharepoint. Previous sharepoint add in was used just to authenticate the user and this has been replaced with Azure Active Directory Authentication (AAD)

The ClientId and Secret has to be taken from Azure Active Directory and needs to be updated in appsettings.json before deploying the solution

**Comment by wauph** [comment]
Hi Prem,


Thanks so much for your reply. Does this mean that Matter Center will be a separate WebApplication from SharePoint Online not like a Provider Hosted Add-in?


Also, please see screen shot if this is where I am going to insert the ClientID? I cannot find where the clientSecret is.

[cid:954db6a1-3e10-4922-a22b-3cbe24004992]


Your documentation does not include this steps you mentioned.


Kind Regards,


Will

________________________________

**Comment by premchandpl** [comment]
Hi

Matter center will be a separate azure web application and there is no sharepoint add in for matter center. 

As part of matter center deployment script, it could have been mentioned in the deployment document regarding the key vault client id,  KeyVaultURI and KeyVaultCertThumbPrint and you need to use these values in application code appsettings.json file

In the deployment document, in Step 9 this information is available. Let me know if more information is required

**Comment by wauph** [comment]
Hi,

Thanks for the information below.

Yes, if you can give me more detailed steps please with regards to step 9.

Kind Regards,

Will



Sent from my Samsung device


-------- Original message --------

**Comment by premchandpl** [comment]
@wauph If the deployment scripts has been executed with out any errors, and if all the steps in the deployment document has been followed correctly, then there is no need to update the General section

The deployment scripts could have updated the appsettings of your web site in the azure portal. If you check you web site appsettings in the azure portal all the required information will be there. The ClientId, Client Secret will be stored in Azure Key Vault and there is no need to update that information any where

At run time, the application will read all this information from AppSettings from the azure portal and even the KeyVaultURI, KeyVaultClientID, KeyVaultCertThumbPrint will also be read from AppSettings from the azure portal

I am sharing my azure web app settings there are there in my azure portal
image
![image](https://cloud.githubusercontent.com/assets/3001352/23290940/7b9fd9e2-fa09-11e6-9720-692550f55927.png)


If you check your azure portal and if you go to you web site settings, then you can see that information. If you want to debug the code from VS, then you can update those values in appsettings.json otherwise updating general section is not needed

**Comment by wauph** [comment]
Hi Prem,


I have successfully run the scripts without error with the settings below in the general section of appsettings.json


[cid:f83b7515-e118-40ff-8f09-8c7c399c00c4]


After successful publishing of the webApplication, the azure website displays a 500 error.


[cid:8da22cbf-40c4-4da8-abf9-c4461afa039d]


At this stage, we haven't done step 9 from the deployment document.


If you can provide us please how to trouble shoot the above, the expected outcome of the site and the publishing steps on step 9.


Kind Regards,


Will U'Ren

user: wauph

________________________________

**Comment by wauph** [comment]
Hi Prem,


I would like to make a follow up.


Kind Regards,


Will

________________________________

**Comment by premchandpl** [comment]
@wauph Let me know how can I follow up with you. My skype id is premchand_76

**Comment by tgarmon** [comment]
@tinsheep I am using your code for this deployment and am also having the exact same issue here. I am very willing to pay you to fix this issue for me. We are so close having this project ready, and we cannot get around this issue after spending many hours. 

@premchandpl , if you have a solution, please post it. The deployment guide does not address this as the link to the for the details has been updated with new information.

**Comment by tinsheep** [comment]
@tgarmon worked for me and should work for you - deployed it successfully with VS2017 - for some reason which i have not resolved yet i can only make it go when the webapp is in the same tenant as the matter center deployment.

**Comment by tgarmon** [comment]
@tinsheep, we have found the issue. Default address in your fork were not updated to our AD address for the application. Another snafoo occurred when the same happened with the resource group name. We are going to make those changes, and try this again next weekend.
