### ISSUE TITLE
Unsure where to put client id and secret

### ISSUE THREAD

**Issue by mfx0r** [Microsoft/mattercenter#671]
Can you please tell me where to put the Client ID and Secret.
I believe it is in the .web project  appsettings.json file but am not sure of this, and the location with the file. as per below
If it is not in this location, please tell me where.
  },
  "General": {
    "Tenant": "msmatter.onmicrosoft.com",
    "AADInstance": "https://login.windows.net/{0}",
    "IsTenantDeployment": true,
    "IsReadOnlyUser": "IsReadOnlyUser",
    "SiteURL": "https://msmatter.sharepoint.com",
    "CentralRepositoryUrl": "https://msmatter.sharepoint.com/sites/catalog",
    "ExchangeServiceURL": "https://outlook.office365.com/ews/Exchange.asmx",
    "MainURL": "http://www.microsoft.com/mattercenter",
    "KeyVaultURI": "",
    "KeyVaultClientID": "",
    "KeyVaultCertThumbPrint": "",
    "IsDevMode": true,
    "GraphUrl": "https://graph.microsoft.com",
    "IsBackwardCompatible": false,
    "IsClientMappedWithHierachy": false,
    "MatterUsersGroup": "Matter Center Users",
    "OverwriteDupliacteFileNameWithDateTimeFor": "Email Only"
  },

**Comment by premchandpl** [comment]
@mfx0r If the deployment scripts has been executed with out any errors, and if all the steps in the deployment document has been followed correctly, then there is no need to update the General section

At run time, the application will read all this information from AppSettings from the azure portal and even the KeyVaultURI, KeyVaultClientID, KeyVaultCertThumbPrint will also be read from AppSettings from the azure portal

I am sharing my azure web app settings there are there in my azure portal
![image](https://cloud.githubusercontent.com/assets/3001352/23290826/9c19208a-fa08-11e6-87cc-432de503fdc3.png)

If you check your azure portal and if you go to you web site settings, then you can see that information. If you want to debug the code from VS, then you can update those values in appsettings.json otherwise updating general section is not needed

let me know whether this issue can be closed

**Comment by mfx0r** [comment]
Would this be from the Web or Vault app?

**Comment by premchandpl** [comment]
@mfx0r This will be from the **web and not vault**. App settings information will be there in the web.

**Comment by mfx0r** [comment]
I only have these in my application settings of the app. Have I missed something?
![capture](https://cloud.githubusercontent.com/assets/25995971/23290974/170ed7f8-faa9-11e6-8102-18ed64abf160.PNG)

**Comment by premchandpl** [comment]
@mfx0r You just have the keys and no values for those keys?

**Comment by mfx0r** [comment]
I do have values but I cut it off to save editing, I notice that I do not have as many keys as you, is there a reason I cannot see these on my web app?
Are the keys that I have enough to make it deploy correctly or do I need others?

**Comment by premchandpl** [comment]
@mfx0r  I have used those things for my development. The things that you are having are sufficient

**Comment by mfx0r** [comment]
I will try and compile now and let you know in a few minutes

**Comment by premchandpl** [comment]
@mfx0r If everything has been setup properly, then you should be in a position to run the matter web app

**Comment by mfx0r** [comment]
I still get the same error, I have reset the appsettings.json file but still receive an invalid secret error

System.AggregateException: One or more errors occurred. ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: AADSTS70002: Error validating credentials. AADSTS50012: Invalid client secret is provided. Trace ID: 1da90812-036b-4cf0-9c30-195e2bc47250
I have reset the key and re-published

**Comment by premchandpl** [comment]
@mfx0r The following powershell script could have update the KeyVault
KeyVault-Config.ps1. You can also check your azure keyvault for those values and validate that client id with azure ad client id

**Comment by mfx0r** [comment]
checking as we speak

**Comment by premchandpl** [comment]
@mfx0r I can come on skype if you need any help premchand_76 is my skype

**Comment by mfx0r** [comment]
I have sent a request

**Comment by mfx0r** [comment]
Have everything working exceptionally well now, thank you very much for the help.
