### ISSUE TITLE
Error provisioning matter center pages

### ISSUE THREAD

**Issue by tasgray** [Microsoft/mattercenter#696]
Hi all,

I've been successful in deploying all steps with the only error being those shown below. The SharePoint user is a global admin, site collection admin and also belongs to the Site Owners group. 

Is there a way to manually setup these pages? I'm hesitant to re-run the script if possible.

Log file also attached. 
[MCDeploy20170315-105714.log.txt](https://github.com/Microsoft/mattercenter/files/843124/MCDeploy20170315-105714.log.txt)

![image](https://cloud.githubusercontent.com/assets/5292389/23928618/d44bd800-0974-11e7-901a-b38c507c50a6.png)

**Comment by kungfulu** [comment]
I had this same issue when I didn't have Administrator or Co-Administrator access in Azure.

**Comment by tasgray** [comment]
@kungfulu To clarify, when the script prompts you for a SharePoint user, you enter credentials which are also Admin / Co-Admin on the Azure subscription?

**Comment by kungfulu** [comment]
I am not sure at this part which piece is being prompted, but in one installation instance I was a O365 Tenant admin, but not an admin in Azure and this was the error I got.  This was the first time I had seen these because I was a Tenant admin and an Azure admin in the other instances.  I contact the person that was in charge of Azure and when he gave me admin privileges.  After that this error was gone and everything installed as expected.

**Comment by Jquintero190** [comment]
I had the same problem, just make sure that the credentials you used for SharePoint prompt in script is added to the site collections administration. you can add them in 
https://<yoursharepointsite.com>/catalog
then click 
Settings -> Site Settings -> Site Collection Administration and add them in the dialog box.

**Comment by amitabhm21** [comment]
Closing this. Looks like @Jquintero190 help resolved this.
