### ISSUE TITLE
Matter Center Images, tasks, calendar not loading 

### ISSUE THREAD

**Issue by mcpsmith** [Microsoft/mattercenter#698]
After Clicking on Matter Center Home I am brought to the SPO site for Matter Center, I click on a matter and notice some images, tasks and calendar do not load

![image](https://cloud.githubusercontent.com/assets/26168907/23964585/5ac0ed6a-098b-11e7-96b6-32ae2f8c2793.png)

**Comment by premchandpl** [comment]
@mcpsmith The issue could have been in spcommon.js file where the path to catalog site collection could have been wrong

Can you check whether the following function "displayHeaderAndFooterContent(isBackwardCompatible)" in the spcommon.js has the following line of code

**var sAssetsLocation = "/sites/catalog/"+oCommonLinks.oMatterCenterAssetsLocation;**

if the value of  of sAssetsLocation is other than the above, please change the code and upload the same spcommon.js to the same location

Let me know if that helps

**Comment by premchandpl** [comment]
@mcpsmith Any updates on this issue. Are you resolve these issues? If not let me know and I will help you to resolve the same

**Comment by premchandpl** [comment]
@mcpsmith regarding the tasks and images not loading, we found issue in our code and we are fixing it. Once it is available I will update you

**Comment by mcpsmith** [comment]
I found the file and updated it in the solution source code. I republished but it did not seem to make a difference.

**Comment by premchandpl** [comment]
@mcpsmith If you come to skype I will resolve the issue for you. My skype is premchand_76

**Comment by mcpsmith** [comment]
Can we Skype on Monday morning around 10am EST? Thank you.

**Comment by premchandpl** [comment]
Will work for me

Sent from my iPhone

On Mar 17, 2017, at 10:21 AM, mcpsmith <notifications@github.com<mailto:notifications@github.com>> wrote:


Can we Skype on Monday morning around 10am EST? Thank you.

**Comment by olegkofm** [comment]
Once problem with invalid images is resolved and they're loaded, they never disappear. It happens because
MatterLanding.js makes references to matterExtraProperties and to documentLibraryName/documentLibraryGUID (in getMatterName) - all of which are undefined there. Search across solution shows that they're defined in Angular controllers but these are not referenced in the landing page anywhere, so with variables missing, code that performs task/calendar checks never gets executed. Once they're added to JS file (even if hardcoded to current matter name/empty array for extra properties), code gets executed and shows correct tasks/calendar events or canned text if none is found.

**Comment by olegkofm** [comment]
The other issue during main matter page load is that both Tasks and Calendar loading operations are deferred until $.get() completed on task and calendar lists respectively. That means that there is very real possibility that code in retrieveListItems() won't be able to find $(".taskBoard") or $(".calendarBoard"). It occurred to me quite often, actually. The fix is to move retrieveListItems() directly into the .done() function of $.get. Not sure, by the way, what happens in .fail() portion (even in existing code)
```
`$.get(taskUrl).done(function () {
	...lot of sTaskPanelText = sTaskPanelText.replace() ops
	$("#taskPane").html(sTaskPanelText);
	ExecuteOrDelayUntilScriptLoaded
	(
		function () 
		{
			var $task = $("#taskPane");
			if ($task) 
			{
			   retrieveListItems(libraryNameSuffix.taskSuffix, oMatterLandingCommonObjects.tasksListQuery, false);
			}
		}, 
		"sp.js"
	);
}).fail(function () {
	taskUrl = listUrl + "/" + getMatterName() + libraryNameSuffix.taskSuffix;
	...lot of sTaskPanelText = sTaskPanelText.replace() ops
	$("#taskPane").html(sTaskPanelText);
});
```

**Comment by premchandpl** [comment]
@mcpsmith @olegkofm The fix has already been checked into github. If you pull the latest code the fix will be there in that code. 

Take the backup of existing matterlanding.js files and ensure that the code inside the [[[]]] has been replaced with proper information from the backup matterlanding.js file

**Comment by mcpsmith** [comment]
@premchandpl  I have updated the two files and republished the matter center. The images still do not show up. I have tried Skype but you appear to be offline.

**Comment by premchandpl** [comment]
@mcpsmith I am available on skype now - premchand_76

**Comment by olegkofm** [comment]
Both MatterLoading.js and spCommon.js contain exactly the same variable oMatterCenterAssetsLocation which, of course, points to different paths (the one in MatterLoading points to "SiteAssets/Matter Center Assets/Matter Landing Assets/" and the one in spCommon points to fully qualified path "https://<tenant>.sharepoint.com/sites/Catalog/SiteAssets/Matter%20Center%20Assets/Common%20Assets/") 
I ended up adding another variable to spCommon.js – oMatterCenterMatterLandingAssetsLocation – pointing it to a specific location where MatterLanding page-specific images are located and carefully walking through MatterLoading.js and updating each IMG path to point to the corresponding location (Common Assets or Matter Landing Assets)

**Comment by mcpsmith** [comment]
@premchandpl - I am on Skype - I added you as premchand_76@microsoft.com - I am msging you from an account named alawsonn

**Comment by premchandpl** [comment]
@mcpsmith my skype id is premchand_76hotmail.com

**Comment by premchandpl** [comment]
@mcpsmith premchand_76@hotmail.com. I added you to skype with id alawsonn

**Comment by premchandpl** [comment]
@mcpsmith closing this github issue as all the issues are resolved

**Comment by mcpsmith** [comment]
@premchandpl  - thank you - issue is resolved now.
