### ISSUE TITLE
Default Values for Matter Center Creation

### ISSUE THREAD

**Issue by mcpsmith** [Microsoft/mattercenter#713]
Is there a way to get default values prepopulated for Matter Creation? Specifically I would like to have defaults specified for:

- Client
- Matter Id
- Make Conflict check fields not required or filled in with default values 
- Default several Team members
- Uncheck include RSS Feed

Thank you.

**Comment by premchandpl** [comment]
@mcpsmith  There is a settings page and in that settings page you can specify the default values for a particular client. The settings page can be accessed from the following url's

1. On  the matter web azure website home page, there will be a link called "Go to Matter Center Home"
2. You will be redirected to matter dash board page
3. In that page click on "Hamburger menu"
![image](https://cloud.githubusercontent.com/assets/3001352/24966174/15bcd540-1f5b-11e7-89d7-7309275b8c03.png)
4. From that menu click on "Settings" link
5. You will be redirected to "Settings" page
6. 
![image](https://cloud.githubusercontent.com/assets/3001352/24966263/4eeeac30-1f5b-11e7-9ac9-771aef670f51.png)
7. Click on your client name
8. And you will be seeing a page as shown below
![image](https://cloud.githubusercontent.com/assets/3001352/24966338/79587492-1f5b-11e7-94f6-6200f2f8d35a.png)
9. From here you can manipulate the default values for each and every client
10. You cant specify default values for the client. But you can specify default values for a particular client since client is the starting point and we cannot specify default value for the client

In order to see the settings page, the login user should be part of SharePoint owners group of the root tenant site collection

**Comment by mcpsmith** [comment]
thank you!!
