### ISSUE TITLE
Title of page is a <number>.aspx and the landing Page have empty web parts

### ISSUE THREAD

**Issue by nikthakur** [Microsoft/mattercenter#787]
Hi,

The matter center seems to be working fine and I can create a matter. There are 2 issues:

A page is created in Client's site site pages library. The name of the page does not use the title of the matter. How do I configure the matter center to use the title of the matter?

The page has some web parts added such as the document library and RSS feed. But the page does not have tab, no tasks, no calendar, etc. It only has those 2 web parts. There are content web parts in place but their content links are empty.

Any suggestions on how to configure the Matter center correctly?

Thanks,

-N

**Comment by nikthakur** [comment]
Our App catalog URL did not match the one in the code. We replaced /sites/catalog to /sites/<our catalog name>

The title of the page is still a number though. Any suggestions name the page the same as Matter name?

Thanks,

-N

**Comment by premchandpl** [comment]
@nikthakur For some scenarios the matter name should not be visible in the URL and that should be confidential. That's the reason we are using GUID. If you want the matter name and not the GUID, you have to modify the code at your end and need to publish again to your azure web site. Hope this clarifies. 

In the MatterProvision.cs file, in the method, CreateMatterLandingPage, there will be, this line code called
string pageName = string.Format(CultureInfo.InvariantCulture, "{0}{1}", matter.MatterGuid, ServiceConstants.ASPX_EXTENSION);

Instead of matter.MatterGuid, you have to replace that with matter.MatterName I think so. Then the page name will be matter name instead of GUID. 

Try this one and let me know if this is going to solve your issue.

Closing this for now. Reopen it, if the above solution is not going to solve, then we can have skype meeting
