### ISSUE TITLE
View document details not linked to the document details page

### ISSUE THREAD

**Issue by nikthakur** [Microsoft/mattercenter#791]
The "View document details" (image below) link is pointing to the root site url of the client. site collection Where is the configuration to point that link to the documentdetails page deployed in the catalog site?

![image](https://user-images.githubusercontent.com/19874285/30897223-efb14718-a309-11e7-8d2a-c903fb197b6c.png) 

Thanks,

-Nik

**Comment by nikthakur** [comment]
Hi @premchandpl, any information on this issue?

**Comment by premchandpl** [comment]
@nikthakur There is one small bug in the code and I know the fix for the same. If you want to fix the same from your end, please do the below steps.

Open the javascript file in any text editor - \tree\master\cloud\src\solution\Microsoft.Legal.MatterCenter.Web\wwwroot\app\dashboard\documentDashboardController.js file. There will be one method in that file called vm.gotoDocumentUrl. 

Replace the below code with in that method. The only change is, instead of **url.replace**, I changed the code to **url.documentClientUrl.replace**

if (vm.assetsuccess) {
                    $window.open(configs.global.repositoryUrl + "/SitePages/documentDetails.aspx?client=" + url.documentClientUrl.replace(configs.uri.SPOsiteURL, "") + "&listguid=" + vm.listguid + "&docguid=" + vm.docguid, "_parent");
                } else {
                    $timeout(function () { $window.open(configs.global.repositoryUrl + "/SitePages/documentDetails.aspx?client=" + url.documentClientUrl.replace(configs.uri.SPOsiteURL, "") + "&listguid=" + vm.listguid + "&docguid=" + vm.docguid, "_parent"); }, 1500);
                }
Publish the code again to your azure web site and do CTRL+F5 in your browser. I have tested this and it is working fine. 

Do the same steps in the file - **tree\master\cloud\src\solution\Microsoft.Legal.MatterCenter.Web\wwwroot\app\document\documents.controller.js** file

**Comment by nikthakur** [comment]
That fixed the issue, thanks you!
